[phases.setup]
nixPkgs = [
  "nodejs_18",
  "chromium",
  "glib",
  "nss",
  "atk",
  "cups",
  "xorg.libXcomposite",
  "xorg.libXrandr",
  "xorg.libXdamage",
  "xorg.libXcursor",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXtst",
  "xorg.libX11",
  "xorg.libXScrnSaver",
  "xorg.libXrender",
  "alsa-lib",
  "pango",
  "cairo",
  "expat",
  "dbus"
]